// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventReq.proto

package ru.splat.protobuf;

public final class EventReqProto {
  private EventReqProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EventReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 transaction_id = 1;
    /**
     * <code>required int64 transaction_id = 1;</code>
     */
    boolean hasTransactionId();
    /**
     * <code>required int64 transaction_id = 1;</code>
     */
    long getTransactionId();

    // required string local_task = 2;
    /**
     * <code>required string local_task = 2;</code>
     */
    boolean hasLocalTask();
    /**
     * <code>required string local_task = 2;</code>
     */
    java.lang.String getLocalTask();
    /**
     * <code>required string local_task = 2;</code>
     */
    com.google.protobuf.ByteString
        getLocalTaskBytes();

    // repeated string tasks = 3;
    /**
     * <code>repeated string tasks = 3;</code>
     */
    java.util.List<java.lang.String>
    getTasksList();
    /**
     * <code>repeated string tasks = 3;</code>
     */
    int getTasksCount();
    /**
     * <code>repeated string tasks = 3;</code>
     */
    java.lang.String getTasks(int index);
    /**
     * <code>repeated string tasks = 3;</code>
     */
    com.google.protobuf.ByteString
        getTasksBytes(int index);

    // repeated int64 events = 4;
    /**
     * <code>repeated int64 events = 4;</code>
     */
    java.util.List<java.lang.Long> getEventsList();
    /**
     * <code>repeated int64 events = 4;</code>
     */
    int getEventsCount();
    /**
     * <code>repeated int64 events = 4;</code>
     */
    long getEvents(int index);

    // repeated int64 selections = 5;
    /**
     * <code>repeated int64 selections = 5;</code>
     */
    java.util.List<java.lang.Long> getSelectionsList();
    /**
     * <code>repeated int64 selections = 5;</code>
     */
    int getSelectionsCount();
    /**
     * <code>repeated int64 selections = 5;</code>
     */
    long getSelections(int index);

    // optional int64 punter_id = 6;
    /**
     * <code>optional int64 punter_id = 6;</code>
     */
    boolean hasPunterId();
    /**
     * <code>optional int64 punter_id = 6;</code>
     */
    long getPunterId();
  }
  /**
   * Protobuf type {@code ru.splat.EventReq}
   */
  public static final class EventReq extends
      com.google.protobuf.GeneratedMessage
      implements EventReqOrBuilder {
    // Use EventReq.newBuilder() to construct.
    private EventReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private EventReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final EventReq defaultInstance;
    public static EventReq getDefaultInstance() {
      return defaultInstance;
    }

    public EventReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private EventReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              transactionId_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              localTask_ = input.readBytes();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                tasks_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              tasks_.add(input.readBytes());
              break;
            }
            case 32: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                events_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000008;
              }
              events_.add(input.readInt64());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008) && input.getBytesUntilLimit() > 0) {
                events_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000008;
              }
              while (input.getBytesUntilLimit() > 0) {
                events_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 40: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                selections_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000010;
              }
              selections_.add(input.readInt64());
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010) && input.getBytesUntilLimit() > 0) {
                selections_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000010;
              }
              while (input.getBytesUntilLimit() > 0) {
                selections_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 48: {
              bitField0_ |= 0x00000004;
              punterId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          tasks_ = new com.google.protobuf.UnmodifiableLazyStringList(tasks_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          events_ = java.util.Collections.unmodifiableList(events_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          selections_ = java.util.Collections.unmodifiableList(selections_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.splat.protobuf.EventReqProto.internal_static_ru_splat_EventReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.splat.protobuf.EventReqProto.internal_static_ru_splat_EventReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.splat.protobuf.EventReqProto.EventReq.class, ru.splat.protobuf.EventReqProto.EventReq.Builder.class);
    }

    public static com.google.protobuf.Parser<EventReq> PARSER =
        new com.google.protobuf.AbstractParser<EventReq>() {
      public EventReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EventReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<EventReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 transaction_id = 1;
    public static final int TRANSACTION_ID_FIELD_NUMBER = 1;
    private long transactionId_;
    /**
     * <code>required int64 transaction_id = 1;</code>
     */
    public boolean hasTransactionId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 transaction_id = 1;</code>
     */
    public long getTransactionId() {
      return transactionId_;
    }

    // required string local_task = 2;
    public static final int LOCAL_TASK_FIELD_NUMBER = 2;
    private java.lang.Object localTask_;
    /**
     * <code>required string local_task = 2;</code>
     */
    public boolean hasLocalTask() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string local_task = 2;</code>
     */
    public java.lang.String getLocalTask() {
      java.lang.Object ref = localTask_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          localTask_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string local_task = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLocalTaskBytes() {
      java.lang.Object ref = localTask_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        localTask_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated string tasks = 3;
    public static final int TASKS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList tasks_;
    /**
     * <code>repeated string tasks = 3;</code>
     */
    public java.util.List<java.lang.String>
        getTasksList() {
      return tasks_;
    }
    /**
     * <code>repeated string tasks = 3;</code>
     */
    public int getTasksCount() {
      return tasks_.size();
    }
    /**
     * <code>repeated string tasks = 3;</code>
     */
    public java.lang.String getTasks(int index) {
      return tasks_.get(index);
    }
    /**
     * <code>repeated string tasks = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTasksBytes(int index) {
      return tasks_.getByteString(index);
    }

    // repeated int64 events = 4;
    public static final int EVENTS_FIELD_NUMBER = 4;
    private java.util.List<java.lang.Long> events_;
    /**
     * <code>repeated int64 events = 4;</code>
     */
    public java.util.List<java.lang.Long>
        getEventsList() {
      return events_;
    }
    /**
     * <code>repeated int64 events = 4;</code>
     */
    public int getEventsCount() {
      return events_.size();
    }
    /**
     * <code>repeated int64 events = 4;</code>
     */
    public long getEvents(int index) {
      return events_.get(index);
    }

    // repeated int64 selections = 5;
    public static final int SELECTIONS_FIELD_NUMBER = 5;
    private java.util.List<java.lang.Long> selections_;
    /**
     * <code>repeated int64 selections = 5;</code>
     */
    public java.util.List<java.lang.Long>
        getSelectionsList() {
      return selections_;
    }
    /**
     * <code>repeated int64 selections = 5;</code>
     */
    public int getSelectionsCount() {
      return selections_.size();
    }
    /**
     * <code>repeated int64 selections = 5;</code>
     */
    public long getSelections(int index) {
      return selections_.get(index);
    }

    // optional int64 punter_id = 6;
    public static final int PUNTER_ID_FIELD_NUMBER = 6;
    private long punterId_;
    /**
     * <code>optional int64 punter_id = 6;</code>
     */
    public boolean hasPunterId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 punter_id = 6;</code>
     */
    public long getPunterId() {
      return punterId_;
    }

    private void initFields() {
      transactionId_ = 0L;
      localTask_ = "";
      tasks_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      events_ = java.util.Collections.emptyList();
      selections_ = java.util.Collections.emptyList();
      punterId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTransactionId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLocalTask()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, transactionId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getLocalTaskBytes());
      }
      for (int i = 0; i < tasks_.size(); i++) {
        output.writeBytes(3, tasks_.getByteString(i));
      }
      for (int i = 0; i < events_.size(); i++) {
        output.writeInt64(4, events_.get(i));
      }
      for (int i = 0; i < selections_.size(); i++) {
        output.writeInt64(5, selections_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(6, punterId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, transactionId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getLocalTaskBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < tasks_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(tasks_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getTasksList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < events_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(events_.get(i));
        }
        size += dataSize;
        size += 1 * getEventsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < selections_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(selections_.get(i));
        }
        size += dataSize;
        size += 1 * getSelectionsList().size();
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, punterId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ru.splat.protobuf.EventReqProto.EventReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.splat.protobuf.EventReqProto.EventReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.splat.protobuf.EventReqProto.EventReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.splat.protobuf.EventReqProto.EventReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.splat.protobuf.EventReqProto.EventReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ru.splat.protobuf.EventReqProto.EventReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ru.splat.protobuf.EventReqProto.EventReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ru.splat.protobuf.EventReqProto.EventReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ru.splat.protobuf.EventReqProto.EventReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ru.splat.protobuf.EventReqProto.EventReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ru.splat.protobuf.EventReqProto.EventReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ru.splat.EventReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ru.splat.protobuf.EventReqProto.EventReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.splat.protobuf.EventReqProto.internal_static_ru_splat_EventReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.splat.protobuf.EventReqProto.internal_static_ru_splat_EventReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.splat.protobuf.EventReqProto.EventReq.class, ru.splat.protobuf.EventReqProto.EventReq.Builder.class);
      }

      // Construct using ru.splat.protobuf.EventReqProto.EventReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        transactionId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        localTask_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        tasks_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        events_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        selections_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        punterId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.splat.protobuf.EventReqProto.internal_static_ru_splat_EventReq_descriptor;
      }

      public ru.splat.protobuf.EventReqProto.EventReq getDefaultInstanceForType() {
        return ru.splat.protobuf.EventReqProto.EventReq.getDefaultInstance();
      }

      public ru.splat.protobuf.EventReqProto.EventReq build() {
        ru.splat.protobuf.EventReqProto.EventReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ru.splat.protobuf.EventReqProto.EventReq buildPartial() {
        ru.splat.protobuf.EventReqProto.EventReq result = new ru.splat.protobuf.EventReqProto.EventReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.transactionId_ = transactionId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.localTask_ = localTask_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          tasks_ = new com.google.protobuf.UnmodifiableLazyStringList(
              tasks_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.tasks_ = tasks_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          events_ = java.util.Collections.unmodifiableList(events_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.events_ = events_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          selections_ = java.util.Collections.unmodifiableList(selections_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.selections_ = selections_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000004;
        }
        result.punterId_ = punterId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.splat.protobuf.EventReqProto.EventReq) {
          return mergeFrom((ru.splat.protobuf.EventReqProto.EventReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.splat.protobuf.EventReqProto.EventReq other) {
        if (other == ru.splat.protobuf.EventReqProto.EventReq.getDefaultInstance()) return this;
        if (other.hasTransactionId()) {
          setTransactionId(other.getTransactionId());
        }
        if (other.hasLocalTask()) {
          bitField0_ |= 0x00000002;
          localTask_ = other.localTask_;
          onChanged();
        }
        if (!other.tasks_.isEmpty()) {
          if (tasks_.isEmpty()) {
            tasks_ = other.tasks_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureTasksIsMutable();
            tasks_.addAll(other.tasks_);
          }
          onChanged();
        }
        if (!other.events_.isEmpty()) {
          if (events_.isEmpty()) {
            events_ = other.events_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureEventsIsMutable();
            events_.addAll(other.events_);
          }
          onChanged();
        }
        if (!other.selections_.isEmpty()) {
          if (selections_.isEmpty()) {
            selections_ = other.selections_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureSelectionsIsMutable();
            selections_.addAll(other.selections_);
          }
          onChanged();
        }
        if (other.hasPunterId()) {
          setPunterId(other.getPunterId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTransactionId()) {
          
          return false;
        }
        if (!hasLocalTask()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.splat.protobuf.EventReqProto.EventReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.splat.protobuf.EventReqProto.EventReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 transaction_id = 1;
      private long transactionId_ ;
      /**
       * <code>required int64 transaction_id = 1;</code>
       */
      public boolean hasTransactionId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 transaction_id = 1;</code>
       */
      public long getTransactionId() {
        return transactionId_;
      }
      /**
       * <code>required int64 transaction_id = 1;</code>
       */
      public Builder setTransactionId(long value) {
        bitField0_ |= 0x00000001;
        transactionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 transaction_id = 1;</code>
       */
      public Builder clearTransactionId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        transactionId_ = 0L;
        onChanged();
        return this;
      }

      // required string local_task = 2;
      private java.lang.Object localTask_ = "";
      /**
       * <code>required string local_task = 2;</code>
       */
      public boolean hasLocalTask() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string local_task = 2;</code>
       */
      public java.lang.String getLocalTask() {
        java.lang.Object ref = localTask_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          localTask_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string local_task = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLocalTaskBytes() {
        java.lang.Object ref = localTask_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          localTask_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string local_task = 2;</code>
       */
      public Builder setLocalTask(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        localTask_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string local_task = 2;</code>
       */
      public Builder clearLocalTask() {
        bitField0_ = (bitField0_ & ~0x00000002);
        localTask_ = getDefaultInstance().getLocalTask();
        onChanged();
        return this;
      }
      /**
       * <code>required string local_task = 2;</code>
       */
      public Builder setLocalTaskBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        localTask_ = value;
        onChanged();
        return this;
      }

      // repeated string tasks = 3;
      private com.google.protobuf.LazyStringList tasks_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureTasksIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          tasks_ = new com.google.protobuf.LazyStringArrayList(tasks_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string tasks = 3;</code>
       */
      public java.util.List<java.lang.String>
          getTasksList() {
        return java.util.Collections.unmodifiableList(tasks_);
      }
      /**
       * <code>repeated string tasks = 3;</code>
       */
      public int getTasksCount() {
        return tasks_.size();
      }
      /**
       * <code>repeated string tasks = 3;</code>
       */
      public java.lang.String getTasks(int index) {
        return tasks_.get(index);
      }
      /**
       * <code>repeated string tasks = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTasksBytes(int index) {
        return tasks_.getByteString(index);
      }
      /**
       * <code>repeated string tasks = 3;</code>
       */
      public Builder setTasks(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTasksIsMutable();
        tasks_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tasks = 3;</code>
       */
      public Builder addTasks(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTasksIsMutable();
        tasks_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tasks = 3;</code>
       */
      public Builder addAllTasks(
          java.lang.Iterable<java.lang.String> values) {
        ensureTasksIsMutable();
        super.addAll(values, tasks_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tasks = 3;</code>
       */
      public Builder clearTasks() {
        tasks_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tasks = 3;</code>
       */
      public Builder addTasksBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTasksIsMutable();
        tasks_.add(value);
        onChanged();
        return this;
      }

      // repeated int64 events = 4;
      private java.util.List<java.lang.Long> events_ = java.util.Collections.emptyList();
      private void ensureEventsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          events_ = new java.util.ArrayList<java.lang.Long>(events_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated int64 events = 4;</code>
       */
      public java.util.List<java.lang.Long>
          getEventsList() {
        return java.util.Collections.unmodifiableList(events_);
      }
      /**
       * <code>repeated int64 events = 4;</code>
       */
      public int getEventsCount() {
        return events_.size();
      }
      /**
       * <code>repeated int64 events = 4;</code>
       */
      public long getEvents(int index) {
        return events_.get(index);
      }
      /**
       * <code>repeated int64 events = 4;</code>
       */
      public Builder setEvents(
          int index, long value) {
        ensureEventsIsMutable();
        events_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 events = 4;</code>
       */
      public Builder addEvents(long value) {
        ensureEventsIsMutable();
        events_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 events = 4;</code>
       */
      public Builder addAllEvents(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureEventsIsMutable();
        super.addAll(values, events_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 events = 4;</code>
       */
      public Builder clearEvents() {
        events_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      // repeated int64 selections = 5;
      private java.util.List<java.lang.Long> selections_ = java.util.Collections.emptyList();
      private void ensureSelectionsIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          selections_ = new java.util.ArrayList<java.lang.Long>(selections_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated int64 selections = 5;</code>
       */
      public java.util.List<java.lang.Long>
          getSelectionsList() {
        return java.util.Collections.unmodifiableList(selections_);
      }
      /**
       * <code>repeated int64 selections = 5;</code>
       */
      public int getSelectionsCount() {
        return selections_.size();
      }
      /**
       * <code>repeated int64 selections = 5;</code>
       */
      public long getSelections(int index) {
        return selections_.get(index);
      }
      /**
       * <code>repeated int64 selections = 5;</code>
       */
      public Builder setSelections(
          int index, long value) {
        ensureSelectionsIsMutable();
        selections_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 selections = 5;</code>
       */
      public Builder addSelections(long value) {
        ensureSelectionsIsMutable();
        selections_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 selections = 5;</code>
       */
      public Builder addAllSelections(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureSelectionsIsMutable();
        super.addAll(values, selections_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 selections = 5;</code>
       */
      public Builder clearSelections() {
        selections_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }

      // optional int64 punter_id = 6;
      private long punterId_ ;
      /**
       * <code>optional int64 punter_id = 6;</code>
       */
      public boolean hasPunterId() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int64 punter_id = 6;</code>
       */
      public long getPunterId() {
        return punterId_;
      }
      /**
       * <code>optional int64 punter_id = 6;</code>
       */
      public Builder setPunterId(long value) {
        bitField0_ |= 0x00000020;
        punterId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 punter_id = 6;</code>
       */
      public Builder clearPunterId() {
        bitField0_ = (bitField0_ & ~0x00000020);
        punterId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ru.splat.EventReq)
    }

    static {
      defaultInstance = new EventReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ru.splat.EventReq)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_splat_EventReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ru_splat_EventReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016EventReq.proto\022\010ru.splat\"|\n\010EventReq\022\026" +
      "\n\016transaction_id\030\001 \002(\003\022\022\n\nlocal_task\030\002 \002" +
      "(\t\022\r\n\005tasks\030\003 \003(\t\022\016\n\006events\030\004 \003(\003\022\022\n\nsel" +
      "ections\030\005 \003(\003\022\021\n\tpunter_id\030\006 \001(\003B\"\n\021ru.s" +
      "plat.protobufB\rEventReqProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ru_splat_EventReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ru_splat_EventReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ru_splat_EventReq_descriptor,
              new java.lang.String[] { "TransactionId", "LocalTask", "Tasks", "Events", "Selections", "PunterId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
