// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventReq.proto

package ru.splat.protobuf;

public final class EventReqProto {
  private EventReqProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EventReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 transaction_id = 1;
    /**
     * <code>required int64 transaction_id = 1;</code>
     */
    boolean hasTransactionId();
    /**
     * <code>required int64 transaction_id = 1;</code>
     */
    long getTransactionId();

    // required int64 local_task = 2;
    /**
     * <code>required int64 local_task = 2;</code>
     */
    boolean hasLocalTask();
    /**
     * <code>required int64 local_task = 2;</code>
     */
    long getLocalTask();

    // required string services = 3;
    /**
     * <code>required string services = 3;</code>
     */
    boolean hasServices();
    /**
     * <code>required string services = 3;</code>
     */
    java.lang.String getServices();
    /**
     * <code>required string services = 3;</code>
     */
    com.google.protobuf.ByteString
        getServicesBytes();

    // repeated int64 event_id = 4;
    /**
     * <code>repeated int64 event_id = 4;</code>
     */
    java.util.List<java.lang.Long> getEventIdList();
    /**
     * <code>repeated int64 event_id = 4;</code>
     */
    int getEventIdCount();
    /**
     * <code>repeated int64 event_id = 4;</code>
     */
    long getEventId(int index);

    // repeated int64 selection_id = 5;
    /**
     * <code>repeated int64 selection_id = 5;</code>
     */
    java.util.List<java.lang.Long> getSelectionIdList();
    /**
     * <code>repeated int64 selection_id = 5;</code>
     */
    int getSelectionIdCount();
    /**
     * <code>repeated int64 selection_id = 5;</code>
     */
    long getSelectionId(int index);
  }
  /**
   * Protobuf type {@code ru.splat.EventReq}
   */
  public static final class EventReq extends
      com.google.protobuf.GeneratedMessage
      implements EventReqOrBuilder {
    // Use EventReq.newBuilder() to construct.
    private EventReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private EventReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final EventReq defaultInstance;
    public static EventReq getDefaultInstance() {
      return defaultInstance;
    }

    public EventReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private EventReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              transactionId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              localTask_ = input.readInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              services_ = input.readBytes();
              break;
            }
            case 32: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                eventId_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000008;
              }
              eventId_.add(input.readInt64());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008) && input.getBytesUntilLimit() > 0) {
                eventId_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000008;
              }
              while (input.getBytesUntilLimit() > 0) {
                eventId_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 40: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                selectionId_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000010;
              }
              selectionId_.add(input.readInt64());
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010) && input.getBytesUntilLimit() > 0) {
                selectionId_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000010;
              }
              while (input.getBytesUntilLimit() > 0) {
                selectionId_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          eventId_ = java.util.Collections.unmodifiableList(eventId_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          selectionId_ = java.util.Collections.unmodifiableList(selectionId_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.splat.protobuf.EventReqProto.internal_static_ru_splat_EventReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.splat.protobuf.EventReqProto.internal_static_ru_splat_EventReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.splat.protobuf.EventReqProto.EventReq.class, ru.splat.protobuf.EventReqProto.EventReq.Builder.class);
    }

    public static com.google.protobuf.Parser<EventReq> PARSER =
        new com.google.protobuf.AbstractParser<EventReq>() {
      public EventReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EventReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<EventReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 transaction_id = 1;
    public static final int TRANSACTION_ID_FIELD_NUMBER = 1;
    private long transactionId_;
    /**
     * <code>required int64 transaction_id = 1;</code>
     */
    public boolean hasTransactionId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 transaction_id = 1;</code>
     */
    public long getTransactionId() {
      return transactionId_;
    }

    // required int64 local_task = 2;
    public static final int LOCAL_TASK_FIELD_NUMBER = 2;
    private long localTask_;
    /**
     * <code>required int64 local_task = 2;</code>
     */
    public boolean hasLocalTask() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 local_task = 2;</code>
     */
    public long getLocalTask() {
      return localTask_;
    }

    // required string services = 3;
    public static final int SERVICES_FIELD_NUMBER = 3;
    private java.lang.Object services_;
    /**
     * <code>required string services = 3;</code>
     */
    public boolean hasServices() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string services = 3;</code>
     */
    public java.lang.String getServices() {
      java.lang.Object ref = services_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          services_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string services = 3;</code>
     */
    public com.google.protobuf.ByteString
        getServicesBytes() {
      java.lang.Object ref = services_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        services_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated int64 event_id = 4;
    public static final int EVENT_ID_FIELD_NUMBER = 4;
    private java.util.List<java.lang.Long> eventId_;
    /**
     * <code>repeated int64 event_id = 4;</code>
     */
    public java.util.List<java.lang.Long>
        getEventIdList() {
      return eventId_;
    }
    /**
     * <code>repeated int64 event_id = 4;</code>
     */
    public int getEventIdCount() {
      return eventId_.size();
    }
    /**
     * <code>repeated int64 event_id = 4;</code>
     */
    public long getEventId(int index) {
      return eventId_.get(index);
    }

    // repeated int64 selection_id = 5;
    public static final int SELECTION_ID_FIELD_NUMBER = 5;
    private java.util.List<java.lang.Long> selectionId_;
    /**
     * <code>repeated int64 selection_id = 5;</code>
     */
    public java.util.List<java.lang.Long>
        getSelectionIdList() {
      return selectionId_;
    }
    /**
     * <code>repeated int64 selection_id = 5;</code>
     */
    public int getSelectionIdCount() {
      return selectionId_.size();
    }
    /**
     * <code>repeated int64 selection_id = 5;</code>
     */
    public long getSelectionId(int index) {
      return selectionId_.get(index);
    }

    private void initFields() {
      transactionId_ = 0L;
      localTask_ = 0L;
      services_ = "";
      eventId_ = java.util.Collections.emptyList();
      selectionId_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTransactionId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLocalTask()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasServices()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, transactionId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, localTask_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getServicesBytes());
      }
      for (int i = 0; i < eventId_.size(); i++) {
        output.writeInt64(4, eventId_.get(i));
      }
      for (int i = 0; i < selectionId_.size(); i++) {
        output.writeInt64(5, selectionId_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, transactionId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, localTask_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getServicesBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < eventId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(eventId_.get(i));
        }
        size += dataSize;
        size += 1 * getEventIdList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < selectionId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(selectionId_.get(i));
        }
        size += dataSize;
        size += 1 * getSelectionIdList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ru.splat.protobuf.EventReqProto.EventReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.splat.protobuf.EventReqProto.EventReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.splat.protobuf.EventReqProto.EventReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.splat.protobuf.EventReqProto.EventReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.splat.protobuf.EventReqProto.EventReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ru.splat.protobuf.EventReqProto.EventReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ru.splat.protobuf.EventReqProto.EventReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ru.splat.protobuf.EventReqProto.EventReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ru.splat.protobuf.EventReqProto.EventReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ru.splat.protobuf.EventReqProto.EventReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ru.splat.protobuf.EventReqProto.EventReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ru.splat.EventReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ru.splat.protobuf.EventReqProto.EventReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.splat.protobuf.EventReqProto.internal_static_ru_splat_EventReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.splat.protobuf.EventReqProto.internal_static_ru_splat_EventReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.splat.protobuf.EventReqProto.EventReq.class, ru.splat.protobuf.EventReqProto.EventReq.Builder.class);
      }

      // Construct using ru.splat.protobuf.EventReqProto.EventReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        transactionId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        localTask_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        services_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        eventId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        selectionId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.splat.protobuf.EventReqProto.internal_static_ru_splat_EventReq_descriptor;
      }

      public ru.splat.protobuf.EventReqProto.EventReq getDefaultInstanceForType() {
        return ru.splat.protobuf.EventReqProto.EventReq.getDefaultInstance();
      }

      public ru.splat.protobuf.EventReqProto.EventReq build() {
        ru.splat.protobuf.EventReqProto.EventReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ru.splat.protobuf.EventReqProto.EventReq buildPartial() {
        ru.splat.protobuf.EventReqProto.EventReq result = new ru.splat.protobuf.EventReqProto.EventReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.transactionId_ = transactionId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.localTask_ = localTask_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.services_ = services_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          eventId_ = java.util.Collections.unmodifiableList(eventId_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.eventId_ = eventId_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          selectionId_ = java.util.Collections.unmodifiableList(selectionId_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.selectionId_ = selectionId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.splat.protobuf.EventReqProto.EventReq) {
          return mergeFrom((ru.splat.protobuf.EventReqProto.EventReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.splat.protobuf.EventReqProto.EventReq other) {
        if (other == ru.splat.protobuf.EventReqProto.EventReq.getDefaultInstance()) return this;
        if (other.hasTransactionId()) {
          setTransactionId(other.getTransactionId());
        }
        if (other.hasLocalTask()) {
          setLocalTask(other.getLocalTask());
        }
        if (other.hasServices()) {
          bitField0_ |= 0x00000004;
          services_ = other.services_;
          onChanged();
        }
        if (!other.eventId_.isEmpty()) {
          if (eventId_.isEmpty()) {
            eventId_ = other.eventId_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureEventIdIsMutable();
            eventId_.addAll(other.eventId_);
          }
          onChanged();
        }
        if (!other.selectionId_.isEmpty()) {
          if (selectionId_.isEmpty()) {
            selectionId_ = other.selectionId_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureSelectionIdIsMutable();
            selectionId_.addAll(other.selectionId_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTransactionId()) {
          
          return false;
        }
        if (!hasLocalTask()) {
          
          return false;
        }
        if (!hasServices()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.splat.protobuf.EventReqProto.EventReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.splat.protobuf.EventReqProto.EventReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 transaction_id = 1;
      private long transactionId_ ;
      /**
       * <code>required int64 transaction_id = 1;</code>
       */
      public boolean hasTransactionId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 transaction_id = 1;</code>
       */
      public long getTransactionId() {
        return transactionId_;
      }
      /**
       * <code>required int64 transaction_id = 1;</code>
       */
      public Builder setTransactionId(long value) {
        bitField0_ |= 0x00000001;
        transactionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 transaction_id = 1;</code>
       */
      public Builder clearTransactionId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        transactionId_ = 0L;
        onChanged();
        return this;
      }

      // required int64 local_task = 2;
      private long localTask_ ;
      /**
       * <code>required int64 local_task = 2;</code>
       */
      public boolean hasLocalTask() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 local_task = 2;</code>
       */
      public long getLocalTask() {
        return localTask_;
      }
      /**
       * <code>required int64 local_task = 2;</code>
       */
      public Builder setLocalTask(long value) {
        bitField0_ |= 0x00000002;
        localTask_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 local_task = 2;</code>
       */
      public Builder clearLocalTask() {
        bitField0_ = (bitField0_ & ~0x00000002);
        localTask_ = 0L;
        onChanged();
        return this;
      }

      // required string services = 3;
      private java.lang.Object services_ = "";
      /**
       * <code>required string services = 3;</code>
       */
      public boolean hasServices() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string services = 3;</code>
       */
      public java.lang.String getServices() {
        java.lang.Object ref = services_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          services_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string services = 3;</code>
       */
      public com.google.protobuf.ByteString
          getServicesBytes() {
        java.lang.Object ref = services_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          services_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string services = 3;</code>
       */
      public Builder setServices(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        services_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string services = 3;</code>
       */
      public Builder clearServices() {
        bitField0_ = (bitField0_ & ~0x00000004);
        services_ = getDefaultInstance().getServices();
        onChanged();
        return this;
      }
      /**
       * <code>required string services = 3;</code>
       */
      public Builder setServicesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        services_ = value;
        onChanged();
        return this;
      }

      // repeated int64 event_id = 4;
      private java.util.List<java.lang.Long> eventId_ = java.util.Collections.emptyList();
      private void ensureEventIdIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          eventId_ = new java.util.ArrayList<java.lang.Long>(eventId_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated int64 event_id = 4;</code>
       */
      public java.util.List<java.lang.Long>
          getEventIdList() {
        return java.util.Collections.unmodifiableList(eventId_);
      }
      /**
       * <code>repeated int64 event_id = 4;</code>
       */
      public int getEventIdCount() {
        return eventId_.size();
      }
      /**
       * <code>repeated int64 event_id = 4;</code>
       */
      public long getEventId(int index) {
        return eventId_.get(index);
      }
      /**
       * <code>repeated int64 event_id = 4;</code>
       */
      public Builder setEventId(
          int index, long value) {
        ensureEventIdIsMutable();
        eventId_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 event_id = 4;</code>
       */
      public Builder addEventId(long value) {
        ensureEventIdIsMutable();
        eventId_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 event_id = 4;</code>
       */
      public Builder addAllEventId(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureEventIdIsMutable();
        super.addAll(values, eventId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 event_id = 4;</code>
       */
      public Builder clearEventId() {
        eventId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      // repeated int64 selection_id = 5;
      private java.util.List<java.lang.Long> selectionId_ = java.util.Collections.emptyList();
      private void ensureSelectionIdIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          selectionId_ = new java.util.ArrayList<java.lang.Long>(selectionId_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated int64 selection_id = 5;</code>
       */
      public java.util.List<java.lang.Long>
          getSelectionIdList() {
        return java.util.Collections.unmodifiableList(selectionId_);
      }
      /**
       * <code>repeated int64 selection_id = 5;</code>
       */
      public int getSelectionIdCount() {
        return selectionId_.size();
      }
      /**
       * <code>repeated int64 selection_id = 5;</code>
       */
      public long getSelectionId(int index) {
        return selectionId_.get(index);
      }
      /**
       * <code>repeated int64 selection_id = 5;</code>
       */
      public Builder setSelectionId(
          int index, long value) {
        ensureSelectionIdIsMutable();
        selectionId_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 selection_id = 5;</code>
       */
      public Builder addSelectionId(long value) {
        ensureSelectionIdIsMutable();
        selectionId_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 selection_id = 5;</code>
       */
      public Builder addAllSelectionId(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureSelectionIdIsMutable();
        super.addAll(values, selectionId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 selection_id = 5;</code>
       */
      public Builder clearSelectionId() {
        selectionId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ru.splat.EventReq)
    }

    static {
      defaultInstance = new EventReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ru.splat.EventReq)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_splat_EventReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ru_splat_EventReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016EventReq.proto\022\010ru.splat\"p\n\010EventReq\022\026" +
      "\n\016transaction_id\030\001 \002(\003\022\022\n\nlocal_task\030\002 \002" +
      "(\003\022\020\n\010services\030\003 \002(\t\022\020\n\010event_id\030\004 \003(\003\022\024" +
      "\n\014selection_id\030\005 \003(\003B\"\n\021ru.splat.protobu" +
      "fB\rEventReqProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ru_splat_EventReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ru_splat_EventReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ru_splat_EventReq_descriptor,
              new java.lang.String[] { "TransactionId", "LocalTask", "Services", "EventId", "SelectionId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
