// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PunterReq.proto

package ru.splat.protobuf;

public final class PunterReqProto {
  private PunterReqProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PunterReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 transaction_id = 1;
    /**
     * <code>required int64 transaction_id = 1;</code>
     */
    boolean hasTransactionId();
    /**
     * <code>required int64 transaction_id = 1;</code>
     */
    long getTransactionId();

    // required string local_task = 2;
    /**
     * <code>required string local_task = 2;</code>
     */
    boolean hasLocalTask();
    /**
     * <code>required string local_task = 2;</code>
     */
    java.lang.String getLocalTask();
    /**
     * <code>required string local_task = 2;</code>
     */
    com.google.protobuf.ByteString
        getLocalTaskBytes();

    // repeated string services = 3;
    /**
     * <code>repeated string services = 3;</code>
     */
    java.util.List<java.lang.String>
    getServicesList();
    /**
     * <code>repeated string services = 3;</code>
     */
    int getServicesCount();
    /**
     * <code>repeated string services = 3;</code>
     */
    java.lang.String getServices(int index);
    /**
     * <code>repeated string services = 3;</code>
     */
    com.google.protobuf.ByteString
        getServicesBytes(int index);

    // optional int64 punter_id = 4;
    /**
     * <code>optional int64 punter_id = 4;</code>
     */
    boolean hasPunterId();
    /**
     * <code>optional int64 punter_id = 4;</code>
     */
    long getPunterId();
  }
  /**
   * Protobuf type {@code ru.splat.PunterReq}
   */
  public static final class PunterReq extends
      com.google.protobuf.GeneratedMessage
      implements PunterReqOrBuilder {
    // Use PunterReq.newBuilder() to construct.
    private PunterReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PunterReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PunterReq defaultInstance;
    public static PunterReq getDefaultInstance() {
      return defaultInstance;
    }

    public PunterReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PunterReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              transactionId_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              localTask_ = input.readBytes();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                services_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              services_.add(input.readBytes());
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              punterId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          services_ = new com.google.protobuf.UnmodifiableLazyStringList(services_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.splat.protobuf.PunterReqProto.internal_static_ru_splat_PunterReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.splat.protobuf.PunterReqProto.internal_static_ru_splat_PunterReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.splat.protobuf.PunterReqProto.PunterReq.class, ru.splat.protobuf.PunterReqProto.PunterReq.Builder.class);
    }

    public static com.google.protobuf.Parser<PunterReq> PARSER =
        new com.google.protobuf.AbstractParser<PunterReq>() {
      public PunterReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PunterReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PunterReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 transaction_id = 1;
    public static final int TRANSACTION_ID_FIELD_NUMBER = 1;
    private long transactionId_;
    /**
     * <code>required int64 transaction_id = 1;</code>
     */
    public boolean hasTransactionId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 transaction_id = 1;</code>
     */
    public long getTransactionId() {
      return transactionId_;
    }

    // required string local_task = 2;
    public static final int LOCAL_TASK_FIELD_NUMBER = 2;
    private java.lang.Object localTask_;
    /**
     * <code>required string local_task = 2;</code>
     */
    public boolean hasLocalTask() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string local_task = 2;</code>
     */
    public java.lang.String getLocalTask() {
      java.lang.Object ref = localTask_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          localTask_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string local_task = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLocalTaskBytes() {
      java.lang.Object ref = localTask_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        localTask_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated string services = 3;
    public static final int SERVICES_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList services_;
    /**
     * <code>repeated string services = 3;</code>
     */
    public java.util.List<java.lang.String>
        getServicesList() {
      return services_;
    }
    /**
     * <code>repeated string services = 3;</code>
     */
    public int getServicesCount() {
      return services_.size();
    }
    /**
     * <code>repeated string services = 3;</code>
     */
    public java.lang.String getServices(int index) {
      return services_.get(index);
    }
    /**
     * <code>repeated string services = 3;</code>
     */
    public com.google.protobuf.ByteString
        getServicesBytes(int index) {
      return services_.getByteString(index);
    }

    // optional int64 punter_id = 4;
    public static final int PUNTER_ID_FIELD_NUMBER = 4;
    private long punterId_;
    /**
     * <code>optional int64 punter_id = 4;</code>
     */
    public boolean hasPunterId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 punter_id = 4;</code>
     */
    public long getPunterId() {
      return punterId_;
    }

    private void initFields() {
      transactionId_ = 0L;
      localTask_ = "";
      services_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      punterId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTransactionId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLocalTask()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, transactionId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getLocalTaskBytes());
      }
      for (int i = 0; i < services_.size(); i++) {
        output.writeBytes(3, services_.getByteString(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(4, punterId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, transactionId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getLocalTaskBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < services_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(services_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getServicesList().size();
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, punterId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ru.splat.protobuf.PunterReqProto.PunterReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.splat.protobuf.PunterReqProto.PunterReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.splat.protobuf.PunterReqProto.PunterReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.splat.protobuf.PunterReqProto.PunterReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.splat.protobuf.PunterReqProto.PunterReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ru.splat.protobuf.PunterReqProto.PunterReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ru.splat.protobuf.PunterReqProto.PunterReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ru.splat.protobuf.PunterReqProto.PunterReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ru.splat.protobuf.PunterReqProto.PunterReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ru.splat.protobuf.PunterReqProto.PunterReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ru.splat.protobuf.PunterReqProto.PunterReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ru.splat.PunterReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ru.splat.protobuf.PunterReqProto.PunterReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.splat.protobuf.PunterReqProto.internal_static_ru_splat_PunterReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.splat.protobuf.PunterReqProto.internal_static_ru_splat_PunterReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.splat.protobuf.PunterReqProto.PunterReq.class, ru.splat.protobuf.PunterReqProto.PunterReq.Builder.class);
      }

      // Construct using ru.splat.protobuf.PunterReqProto.PunterReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        transactionId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        localTask_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        services_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        punterId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.splat.protobuf.PunterReqProto.internal_static_ru_splat_PunterReq_descriptor;
      }

      public ru.splat.protobuf.PunterReqProto.PunterReq getDefaultInstanceForType() {
        return ru.splat.protobuf.PunterReqProto.PunterReq.getDefaultInstance();
      }

      public ru.splat.protobuf.PunterReqProto.PunterReq build() {
        ru.splat.protobuf.PunterReqProto.PunterReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ru.splat.protobuf.PunterReqProto.PunterReq buildPartial() {
        ru.splat.protobuf.PunterReqProto.PunterReq result = new ru.splat.protobuf.PunterReqProto.PunterReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.transactionId_ = transactionId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.localTask_ = localTask_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          services_ = new com.google.protobuf.UnmodifiableLazyStringList(
              services_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.services_ = services_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.punterId_ = punterId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.splat.protobuf.PunterReqProto.PunterReq) {
          return mergeFrom((ru.splat.protobuf.PunterReqProto.PunterReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.splat.protobuf.PunterReqProto.PunterReq other) {
        if (other == ru.splat.protobuf.PunterReqProto.PunterReq.getDefaultInstance()) return this;
        if (other.hasTransactionId()) {
          setTransactionId(other.getTransactionId());
        }
        if (other.hasLocalTask()) {
          bitField0_ |= 0x00000002;
          localTask_ = other.localTask_;
          onChanged();
        }
        if (!other.services_.isEmpty()) {
          if (services_.isEmpty()) {
            services_ = other.services_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureServicesIsMutable();
            services_.addAll(other.services_);
          }
          onChanged();
        }
        if (other.hasPunterId()) {
          setPunterId(other.getPunterId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTransactionId()) {
          
          return false;
        }
        if (!hasLocalTask()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.splat.protobuf.PunterReqProto.PunterReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.splat.protobuf.PunterReqProto.PunterReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 transaction_id = 1;
      private long transactionId_ ;
      /**
       * <code>required int64 transaction_id = 1;</code>
       */
      public boolean hasTransactionId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 transaction_id = 1;</code>
       */
      public long getTransactionId() {
        return transactionId_;
      }
      /**
       * <code>required int64 transaction_id = 1;</code>
       */
      public Builder setTransactionId(long value) {
        bitField0_ |= 0x00000001;
        transactionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 transaction_id = 1;</code>
       */
      public Builder clearTransactionId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        transactionId_ = 0L;
        onChanged();
        return this;
      }

      // required string local_task = 2;
      private java.lang.Object localTask_ = "";
      /**
       * <code>required string local_task = 2;</code>
       */
      public boolean hasLocalTask() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string local_task = 2;</code>
       */
      public java.lang.String getLocalTask() {
        java.lang.Object ref = localTask_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          localTask_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string local_task = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLocalTaskBytes() {
        java.lang.Object ref = localTask_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          localTask_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string local_task = 2;</code>
       */
      public Builder setLocalTask(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        localTask_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string local_task = 2;</code>
       */
      public Builder clearLocalTask() {
        bitField0_ = (bitField0_ & ~0x00000002);
        localTask_ = getDefaultInstance().getLocalTask();
        onChanged();
        return this;
      }
      /**
       * <code>required string local_task = 2;</code>
       */
      public Builder setLocalTaskBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        localTask_ = value;
        onChanged();
        return this;
      }

      // repeated string services = 3;
      private com.google.protobuf.LazyStringList services_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureServicesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          services_ = new com.google.protobuf.LazyStringArrayList(services_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string services = 3;</code>
       */
      public java.util.List<java.lang.String>
          getServicesList() {
        return java.util.Collections.unmodifiableList(services_);
      }
      /**
       * <code>repeated string services = 3;</code>
       */
      public int getServicesCount() {
        return services_.size();
      }
      /**
       * <code>repeated string services = 3;</code>
       */
      public java.lang.String getServices(int index) {
        return services_.get(index);
      }
      /**
       * <code>repeated string services = 3;</code>
       */
      public com.google.protobuf.ByteString
          getServicesBytes(int index) {
        return services_.getByteString(index);
      }
      /**
       * <code>repeated string services = 3;</code>
       */
      public Builder setServices(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureServicesIsMutable();
        services_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string services = 3;</code>
       */
      public Builder addServices(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureServicesIsMutable();
        services_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string services = 3;</code>
       */
      public Builder addAllServices(
          java.lang.Iterable<java.lang.String> values) {
        ensureServicesIsMutable();
        super.addAll(values, services_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string services = 3;</code>
       */
      public Builder clearServices() {
        services_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string services = 3;</code>
       */
      public Builder addServicesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureServicesIsMutable();
        services_.add(value);
        onChanged();
        return this;
      }

      // optional int64 punter_id = 4;
      private long punterId_ ;
      /**
       * <code>optional int64 punter_id = 4;</code>
       */
      public boolean hasPunterId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 punter_id = 4;</code>
       */
      public long getPunterId() {
        return punterId_;
      }
      /**
       * <code>optional int64 punter_id = 4;</code>
       */
      public Builder setPunterId(long value) {
        bitField0_ |= 0x00000008;
        punterId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 punter_id = 4;</code>
       */
      public Builder clearPunterId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        punterId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ru.splat.PunterReq)
    }

    static {
      defaultInstance = new PunterReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ru.splat.PunterReq)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_splat_PunterReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ru_splat_PunterReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017PunterReq.proto\022\010ru.splat\"\\\n\tPunterReq" +
      "\022\026\n\016transaction_id\030\001 \002(\003\022\022\n\nlocal_task\030\002" +
      " \002(\t\022\020\n\010services\030\003 \003(\t\022\021\n\tpunter_id\030\004 \001(" +
      "\003B#\n\021ru.splat.protobufB\016PunterReqProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ru_splat_PunterReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ru_splat_PunterReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ru_splat_PunterReq_descriptor,
              new java.lang.String[] { "TransactionId", "LocalTask", "Services", "PunterId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
