// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BillingReq.proto

package ru.splat.splattrainee.protobuf;

public final class BillingWithdrawProto {
  private BillingWithdrawProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface WithdrawCashOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 transactionId = 1;
    /**
     * <code>required int64 transactionId = 1;</code>
     */
    boolean hasTransactionId();
    /**
     * <code>required int64 transactionId = 1;</code>
     */
    long getTransactionId();

    // required int64 local_task = 2;
    /**
     * <code>required int64 local_task = 2;</code>
     */
    boolean hasLocalTask();
    /**
     * <code>required int64 local_task = 2;</code>
     */
    long getLocalTask();

    // repeated string services = 3;
    /**
     * <code>repeated string services = 3;</code>
     */
    java.util.List<java.lang.String>
    getServicesList();
    /**
     * <code>repeated string services = 3;</code>
     */
    int getServicesCount();
    /**
     * <code>repeated string services = 3;</code>
     */
    java.lang.String getServices(int index);
    /**
     * <code>repeated string services = 3;</code>
     */
    com.google.protobuf.ByteString
        getServicesBytes(int index);

    // required int64 user_id = 4;
    /**
     * <code>required int64 user_id = 4;</code>
     */
    boolean hasUserId();
    /**
     * <code>required int64 user_id = 4;</code>
     */
    long getUserId();

    // required int32 sum = 5;
    /**
     * <code>required int32 sum = 5;</code>
     */
    boolean hasSum();
    /**
     * <code>required int32 sum = 5;</code>
     */
    int getSum();
  }
  /**
   * Protobuf type {@code ru.splat.splattrainee.WithdrawCash}
   */
  public static final class WithdrawCash extends
      com.google.protobuf.GeneratedMessage
      implements WithdrawCashOrBuilder {
    // Use WithdrawCash.newBuilder() to construct.
    private WithdrawCash(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private WithdrawCash(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final WithdrawCash defaultInstance;
    public static WithdrawCash getDefaultInstance() {
      return defaultInstance;
    }

    public WithdrawCash getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private WithdrawCash(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              transactionId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              localTask_ = input.readInt64();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                services_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              services_.add(input.readBytes());
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              userId_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000008;
              sum_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          services_ = new com.google.protobuf.UnmodifiableLazyStringList(services_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.splat.splattrainee.protobuf.BillingWithdrawProto.internal_static_ru_splat_splattrainee_WithdrawCash_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.splat.splattrainee.protobuf.BillingWithdrawProto.internal_static_ru_splat_splattrainee_WithdrawCash_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.splat.splattrainee.protobuf.BillingWithdrawProto.WithdrawCash.class, ru.splat.splattrainee.protobuf.BillingWithdrawProto.WithdrawCash.Builder.class);
    }

    public static com.google.protobuf.Parser<WithdrawCash> PARSER =
        new com.google.protobuf.AbstractParser<WithdrawCash>() {
      public WithdrawCash parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WithdrawCash(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<WithdrawCash> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 transactionId = 1;
    public static final int TRANSACTIONID_FIELD_NUMBER = 1;
    private long transactionId_;
    /**
     * <code>required int64 transactionId = 1;</code>
     */
    public boolean hasTransactionId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 transactionId = 1;</code>
     */
    public long getTransactionId() {
      return transactionId_;
    }

    // required int64 local_task = 2;
    public static final int LOCAL_TASK_FIELD_NUMBER = 2;
    private long localTask_;
    /**
     * <code>required int64 local_task = 2;</code>
     */
    public boolean hasLocalTask() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 local_task = 2;</code>
     */
    public long getLocalTask() {
      return localTask_;
    }

    // repeated string services = 3;
    public static final int SERVICES_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList services_;
    /**
     * <code>repeated string services = 3;</code>
     */
    public java.util.List<java.lang.String>
        getServicesList() {
      return services_;
    }
    /**
     * <code>repeated string services = 3;</code>
     */
    public int getServicesCount() {
      return services_.size();
    }
    /**
     * <code>repeated string services = 3;</code>
     */
    public java.lang.String getServices(int index) {
      return services_.get(index);
    }
    /**
     * <code>repeated string services = 3;</code>
     */
    public com.google.protobuf.ByteString
        getServicesBytes(int index) {
      return services_.getByteString(index);
    }

    // required int64 user_id = 4;
    public static final int USER_ID_FIELD_NUMBER = 4;
    private long userId_;
    /**
     * <code>required int64 user_id = 4;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 user_id = 4;</code>
     */
    public long getUserId() {
      return userId_;
    }

    // required int32 sum = 5;
    public static final int SUM_FIELD_NUMBER = 5;
    private int sum_;
    /**
     * <code>required int32 sum = 5;</code>
     */
    public boolean hasSum() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 sum = 5;</code>
     */
    public int getSum() {
      return sum_;
    }

    private void initFields() {
      transactionId_ = 0L;
      localTask_ = 0L;
      services_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      userId_ = 0L;
      sum_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTransactionId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLocalTask()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, transactionId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, localTask_);
      }
      for (int i = 0; i < services_.size(); i++) {
        output.writeBytes(3, services_.getByteString(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(4, userId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(5, sum_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, transactionId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, localTask_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < services_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(services_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getServicesList().size();
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, userId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, sum_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ru.splat.splattrainee.protobuf.BillingWithdrawProto.WithdrawCash parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.splat.splattrainee.protobuf.BillingWithdrawProto.WithdrawCash parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.splat.splattrainee.protobuf.BillingWithdrawProto.WithdrawCash parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.splat.splattrainee.protobuf.BillingWithdrawProto.WithdrawCash parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.splat.splattrainee.protobuf.BillingWithdrawProto.WithdrawCash parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ru.splat.splattrainee.protobuf.BillingWithdrawProto.WithdrawCash parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ru.splat.splattrainee.protobuf.BillingWithdrawProto.WithdrawCash parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ru.splat.splattrainee.protobuf.BillingWithdrawProto.WithdrawCash parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ru.splat.splattrainee.protobuf.BillingWithdrawProto.WithdrawCash parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ru.splat.splattrainee.protobuf.BillingWithdrawProto.WithdrawCash parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ru.splat.splattrainee.protobuf.BillingWithdrawProto.WithdrawCash prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ru.splat.splattrainee.WithdrawCash}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ru.splat.splattrainee.protobuf.BillingWithdrawProto.WithdrawCashOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.splat.splattrainee.protobuf.BillingWithdrawProto.internal_static_ru_splat_splattrainee_WithdrawCash_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.splat.splattrainee.protobuf.BillingWithdrawProto.internal_static_ru_splat_splattrainee_WithdrawCash_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.splat.splattrainee.protobuf.BillingWithdrawProto.WithdrawCash.class, ru.splat.splattrainee.protobuf.BillingWithdrawProto.WithdrawCash.Builder.class);
      }

      // Construct using BillingWithdrawProto.WithdrawCash.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        transactionId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        localTask_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        services_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        userId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        sum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.splat.splattrainee.protobuf.BillingWithdrawProto.internal_static_ru_splat_splattrainee_WithdrawCash_descriptor;
      }

      public ru.splat.splattrainee.protobuf.BillingWithdrawProto.WithdrawCash getDefaultInstanceForType() {
        return ru.splat.splattrainee.protobuf.BillingWithdrawProto.WithdrawCash.getDefaultInstance();
      }

      public ru.splat.splattrainee.protobuf.BillingWithdrawProto.WithdrawCash build() {
        ru.splat.splattrainee.protobuf.BillingWithdrawProto.WithdrawCash result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ru.splat.splattrainee.protobuf.BillingWithdrawProto.WithdrawCash buildPartial() {
        ru.splat.splattrainee.protobuf.BillingWithdrawProto.WithdrawCash result = new ru.splat.splattrainee.protobuf.BillingWithdrawProto.WithdrawCash(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.transactionId_ = transactionId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.localTask_ = localTask_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          services_ = new com.google.protobuf.UnmodifiableLazyStringList(
              services_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.services_ = services_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.sum_ = sum_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.splat.splattrainee.protobuf.BillingWithdrawProto.WithdrawCash) {
          return mergeFrom((ru.splat.splattrainee.protobuf.BillingWithdrawProto.WithdrawCash)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.splat.splattrainee.protobuf.BillingWithdrawProto.WithdrawCash other) {
        if (other == ru.splat.splattrainee.protobuf.BillingWithdrawProto.WithdrawCash.getDefaultInstance()) return this;
        if (other.hasTransactionId()) {
          setTransactionId(other.getTransactionId());
        }
        if (other.hasLocalTask()) {
          setLocalTask(other.getLocalTask());
        }
        if (!other.services_.isEmpty()) {
          if (services_.isEmpty()) {
            services_ = other.services_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureServicesIsMutable();
            services_.addAll(other.services_);
          }
          onChanged();
        }
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasSum()) {
          setSum(other.getSum());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTransactionId()) {
          
          return false;
        }
        if (!hasLocalTask()) {
          
          return false;
        }
        if (!hasUserId()) {
          
          return false;
        }
        if (!hasSum()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.splat.splattrainee.protobuf.BillingWithdrawProto.WithdrawCash parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.splat.splattrainee.protobuf.BillingWithdrawProto.WithdrawCash) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 transactionId = 1;
      private long transactionId_ ;
      /**
       * <code>required int64 transactionId = 1;</code>
       */
      public boolean hasTransactionId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 transactionId = 1;</code>
       */
      public long getTransactionId() {
        return transactionId_;
      }
      /**
       * <code>required int64 transactionId = 1;</code>
       */
      public Builder setTransactionId(long value) {
        bitField0_ |= 0x00000001;
        transactionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 transactionId = 1;</code>
       */
      public Builder clearTransactionId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        transactionId_ = 0L;
        onChanged();
        return this;
      }

      // required int64 local_task = 2;
      private long localTask_ ;
      /**
       * <code>required int64 local_task = 2;</code>
       */
      public boolean hasLocalTask() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 local_task = 2;</code>
       */
      public long getLocalTask() {
        return localTask_;
      }
      /**
       * <code>required int64 local_task = 2;</code>
       */
      public Builder setLocalTask(long value) {
        bitField0_ |= 0x00000002;
        localTask_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 local_task = 2;</code>
       */
      public Builder clearLocalTask() {
        bitField0_ = (bitField0_ & ~0x00000002);
        localTask_ = 0L;
        onChanged();
        return this;
      }

      // repeated string services = 3;
      private com.google.protobuf.LazyStringList services_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureServicesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          services_ = new com.google.protobuf.LazyStringArrayList(services_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string services = 3;</code>
       */
      public java.util.List<java.lang.String>
          getServicesList() {
        return java.util.Collections.unmodifiableList(services_);
      }
      /**
       * <code>repeated string services = 3;</code>
       */
      public int getServicesCount() {
        return services_.size();
      }
      /**
       * <code>repeated string services = 3;</code>
       */
      public java.lang.String getServices(int index) {
        return services_.get(index);
      }
      /**
       * <code>repeated string services = 3;</code>
       */
      public com.google.protobuf.ByteString
          getServicesBytes(int index) {
        return services_.getByteString(index);
      }
      /**
       * <code>repeated string services = 3;</code>
       */
      public Builder setServices(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureServicesIsMutable();
        services_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string services = 3;</code>
       */
      public Builder addServices(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureServicesIsMutable();
        services_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string services = 3;</code>
       */
      public Builder addAllServices(
          java.lang.Iterable<java.lang.String> values) {
        ensureServicesIsMutable();
        super.addAll(values, services_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string services = 3;</code>
       */
      public Builder clearServices() {
        services_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string services = 3;</code>
       */
      public Builder addServicesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureServicesIsMutable();
        services_.add(value);
        onChanged();
        return this;
      }

      // required int64 user_id = 4;
      private long userId_ ;
      /**
       * <code>required int64 user_id = 4;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int64 user_id = 4;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>required int64 user_id = 4;</code>
       */
      public Builder setUserId(long value) {
        bitField0_ |= 0x00000008;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 user_id = 4;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        userId_ = 0L;
        onChanged();
        return this;
      }

      // required int32 sum = 5;
      private int sum_ ;
      /**
       * <code>required int32 sum = 5;</code>
       */
      public boolean hasSum() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 sum = 5;</code>
       */
      public int getSum() {
        return sum_;
      }
      /**
       * <code>required int32 sum = 5;</code>
       */
      public Builder setSum(int value) {
        bitField0_ |= 0x00000010;
        sum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 sum = 5;</code>
       */
      public Builder clearSum() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sum_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ru.splat.splattrainee.WithdrawCash)
    }

    static {
      defaultInstance = new WithdrawCash(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ru.splat.splattrainee.WithdrawCash)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_splat_splattrainee_WithdrawCash_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ru_splat_splattrainee_WithdrawCash_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022WithdrawCash.proto\022\025ru.splat.splattrai" +
      "nee\"i\n\014WithdrawCash\022\025\n\rtransactionId\030\001 \002" +
      "(\003\022\022\n\nlocal_task\030\002 \002(\003\022\020\n\010services\030\003 \003(\t" +
      "\022\017\n\007user_id\030\004 \002(\003\022\013\n\003sum\030\005 \002(\005B6\n\036ru.spl" +
      "at.splattrainee.protobufB\024BillingWithdra" +
      "wProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ru_splat_splattrainee_WithdrawCash_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ru_splat_splattrainee_WithdrawCash_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ru_splat_splattrainee_WithdrawCash_descriptor,
              new java.lang.String[] { "TransactionId", "LocalTask", "Services", "UserId", "Sum", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
